[package]
name = "fallible_alloc"
version = "0.1.0"
authors = ["zkud <kudirko.anton@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/zkud/fallible-alloc"
keywords = ["allocation", "fallible", "std", "stable"]

[dependencies]
