name: failable_alloc

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    
  tests:
    name: Tests
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test
      
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        rustup component add rustfmt
        rustup component add clippy
        rustfmt --version
        npm i
    - name: Formatting lint
      run: rustfmt ./src/lib.rs --check
    - name: Semantic lint
      run: cargo clippy
  
  code-cov:
    name: Code Coverage
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.0'
          args: '--ignore-tests -- --test-threads 4'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2.2.3
        with:
          name: code-coverage-report
          path: cobertura.xml
  
  code-scan:
    name: Code Scan

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports